### ISSUE TITLE
系列一 make api  并不能生成 user_http.pb.go 是不是你的 kratos命令行版本过低

### ISSUE THREAD

**Issue by bytegolang** [aliliin/kratos-shop#1]
系列一 make api  并不能生成 user_http.pb.go 是不是你的 kratos命令行版本过低
我的是 v2.1.5

**Comment by aliliin** [comment]
你好，user 服务并未提供 http 的服务，编写 user.proto 文件的是时候并未加入 http 相关的服务。[kratos 框架具体参考](https://go-kratos.dev/docs/component/api)

**Comment by aliliin** [comment]
> 系列一 make api 并不能生成 user_http.pb.go 是不是你的 kratos命令行版本过低 我的是 v2.1.5

你好，user 服务编写 user.proto 的时候并未指定要生成 http 对应的 pb.go 文件

**Comment by bytegolang** [comment]
> > 系列一 make api 并不能生成 user_http.pb.go 是不是你的 kratos命令行版本过低 我的是 v2.1.5
> 
> 你好，user 服务编写 user.proto 的时候并未指定要生成 http 对应的 pb.go 文件
![image](https://user-images.githubusercontent.com/16700482/155043507-7cef9416-9f2a-4bdb-89cf-79a4fdc62fc4.png)

**Comment by aliliin** [comment]
> > > 系列一 make api 并不能生成 user_http.pb.go 是不是你的 kratos命令行版本过低 我的是 v2.1.5
> > 
> > 
> > 你好，user 服务编写 user.proto 的时候并未指定要生成 http 对应的 pb.go 文件
> > ![image](https://user-images.githubusercontent.com/16700482/155043507-7cef9416-9f2a-4bdb-89cf-79a4fdc62fc4.png)

😂，不好意思，这个应该是我多写了。
